package com.funilaria.api.enums;

public enum PecaEnum {
    CAPO,
    TETO,
    TAMPA_TRASEIRA,
    PARALAMA_DIANTEIRO_ESQUERDO,
    PARALAMA_DIANTEIRO_DIREITO,
    PORTA_DIANTEIRA_ESQUERDA,
    PORTA_DIANTEIRA_DIREITA,
    PORTA_TRASEIRA_ESQUERDA,
    PORTA_TRASEIRA_DIREITA,
    LATERAL_TRASEIRA_ESQUERDA,
    LATERAL_TRASEIRA_DIREITA,
    PARACHOQUE_DIANTEIRO,
    PARACHOQUE_TRASEIRO,
    COLUNA_LADO_ESQUERDO,
    COLUNA_LADO_DIREITO,
    POLIMENTO,
    PINTURA,
    OUTROS
}
